# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(998, 780)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_push = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_push.setGeometry(QtCore.QRect(820, 250, 91, 31))
        self.pushButton_push.setObjectName("pushButton_push")
        import pyqtgraph.opengl as gl
        self.graphicsView = gl.GLViewWidget(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(20, 60, 711, 691))
        self.graphicsView.setObjectName("graphicsView")
        self.pushButton_loadFile = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_loadFile.setGeometry(QtCore.QRect(640, 20, 91, 31))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_loadFile.setIcon(icon)
        self.pushButton_loadFile.setObjectName("pushButton_loadFile")
        self.listWidget_customData = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_customData.setGeometry(QtCore.QRect(750, 60, 231, 231))
        self.listWidget_customData.setObjectName("listWidget_customData")
        self.label_inputData = QtWidgets.QLabel(self.centralwidget)
        self.label_inputData.setGeometry(QtCore.QRect(820, 80, 91, 17))
        self.label_inputData.setObjectName("label_inputData")
        self.label_latitude = QtWidgets.QLabel(self.centralwidget)
        self.label_latitude.setGeometry(QtCore.QRect(770, 120, 81, 29))
        self.label_latitude.setObjectName("label_latitude")
        self.textEdit_latitude = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_latitude.setGeometry(QtCore.QRect(860, 120, 97, 31))
        self.textEdit_latitude.setObjectName("textEdit_latitude")
        self.textEdit_longtitude = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_longtitude.setGeometry(QtCore.QRect(860, 160, 97, 31))
        self.textEdit_longtitude.setObjectName("textEdit_longtitude")
        self.textEdit_depth = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_depth.setGeometry(QtCore.QRect(860, 200, 97, 31))
        self.textEdit_depth.setObjectName("textEdit_depth")
        self.label_longtitude = QtWidgets.QLabel(self.centralwidget)
        self.label_longtitude.setGeometry(QtCore.QRect(770, 160, 81, 29))
        self.label_longtitude.setObjectName("label_longtitude")
        self.label_depth = QtWidgets.QLabel(self.centralwidget)
        self.label_depth.setGeometry(QtCore.QRect(770, 200, 81, 29))
        self.label_depth.setObjectName("label_depth")
        self.pushButton_reset = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_reset.setGeometry(QtCore.QRect(750, 720, 231, 31))
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.pushButton_updateDB = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_updateDB.setGeometry(QtCore.QRect(760, 470, 211, 31))
        self.pushButton_updateDB.setObjectName("pushButton_updateDB")
        self.listWidget_filePath = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_filePath.setGeometry(QtCore.QRect(20, 20, 611, 31))
        self.listWidget_filePath.setObjectName("listWidget_filePath")
        self.label_filePath = QtWidgets.QLabel(self.centralwidget)
        self.label_filePath.setGeometry(QtCore.QRect(30, 20, 591, 31))
        self.label_filePath.setText("")
        self.label_filePath.setObjectName("label_filePath")
        self.label_colorMap = QtWidgets.QLabel(self.centralwidget)
        self.label_colorMap.setGeometry(QtCore.QRect(750, 310, 231, 21))
        self.label_colorMap.setAlignment(QtCore.Qt.AlignCenter)
        self.label_colorMap.setObjectName("label_colorMap")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(750, 300, 231, 81))
        self.listWidget.setObjectName("listWidget")
        self.comboBox_colorMap = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_colorMap.setGeometry(QtCore.QRect(760, 340, 211, 27))
        self.comboBox_colorMap.setCurrentText("")
        self.comboBox_colorMap.setObjectName("comboBox_colorMap")
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setGeometry(QtCore.QRect(750, 390, 231, 161))
        self.listWidget_2.setObjectName("listWidget_2")
        self.label_database = QtWidgets.QLabel(self.centralwidget)
        self.label_database.setGeometry(QtCore.QRect(750, 400, 231, 21))
        self.label_database.setAlignment(QtCore.Qt.AlignCenter)
        self.label_database.setObjectName("label_database")
        self.pushButton_connectDB = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_connectDB.setGeometry(QtCore.QRect(760, 430, 211, 31))
        self.pushButton_connectDB.setObjectName("pushButton_connectDB")
        self.pushButton_disconnectDB = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_disconnectDB.setGeometry(QtCore.QRect(760, 510, 211, 31))
        self.pushButton_disconnectDB.setObjectName("pushButton_disconnectDB")
        self.pushButton_virtualData = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_virtualData.setGeometry(QtCore.QRect(750, 680, 231, 31))
        self.pushButton_virtualData.setObjectName("pushButton_virtualData")
        self.listWidget_2.raise_()
        self.listWidget.raise_()
        self.listWidget_customData.raise_()
        self.graphicsView.raise_()
        self.pushButton_loadFile.raise_()
        self.label_inputData.raise_()
        self.label_latitude.raise_()
        self.textEdit_latitude.raise_()
        self.textEdit_longtitude.raise_()
        self.textEdit_depth.raise_()
        self.pushButton_push.raise_()
        self.label_longtitude.raise_()
        self.label_depth.raise_()
        self.pushButton_reset.raise_()
        self.pushButton_updateDB.raise_()
        self.listWidget_filePath.raise_()
        self.label_filePath.raise_()
        self.label_colorMap.raise_()
        self.comboBox_colorMap.raise_()
        self.label_database.raise_()
        self.pushButton_connectDB.raise_()
        self.pushButton_disconnectDB.raise_()
        self.pushButton_virtualData.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.comboBox_colorMap.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_push.setText(_translate("MainWindow", "Push"))
        self.pushButton_loadFile.setText(_translate("MainWindow", " Load File"))
        self.label_inputData.setText(_translate("MainWindow", "Custom Data"))
        self.label_latitude.setText(_translate("MainWindow", "Latitude"))
        self.label_longtitude.setText(_translate("MainWindow", "Longtitude"))
        self.label_depth.setText(_translate("MainWindow", "Depth"))
        self.pushButton_reset.setText(_translate("MainWindow", "Reset"))
        self.pushButton_updateDB.setText(_translate("MainWindow", "Update"))
        self.label_colorMap.setText(_translate("MainWindow", "ColorMap"))
        self.label_database.setText(_translate("MainWindow", "Database"))
        self.pushButton_connectDB.setText(_translate("MainWindow", "Connect"))
        self.pushButton_disconnectDB.setText(_translate("MainWindow", "Disconnect"))
        self.pushButton_virtualData.setText(_translate("MainWindow", "Virtual Data"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

